/*
** Orx struct types conversions
** (generated with conversion.py)
*/


#ifndef __LORX_CONUTYPE_H__
#define __LORX_CONUTYPE_H__

#include <lua.h>
#include <orx.h>
#include "helpers.h"

LORX_API int lorx_orxAABOX_to_luserdata_struct(lua_State *L, const orxAABOX *src);
LORX_API orxAABOX lorx_luserdata_to_orxAABOX_struct(lua_State *L, int i);
LORX_API orxAABOX* lorx_luserdata_to_orxAABOX(lua_State *L, int i);
LORX_API const orxAABOX* lorx_luserdata_to_orxAABOX_const(lua_State *L, int i);
LORX_API int lorx_orxANIM_to_luserdata(lua_State *L, orxANIM* src);
LORX_API int lorx_orxANIM_to_luserdata_const(lua_State *L, const orxANIM* src);
LORX_API orxANIM* lorx_luserdata_to_orxANIM(lua_State *L, int i);
LORX_API const orxANIM* lorx_luserdata_to_orxANIM_const(lua_State *L, int i);
LORX_API int lorx_orxANIMPOINTER_to_luserdata(lua_State *L, orxANIMPOINTER* src);
LORX_API int lorx_orxANIMPOINTER_to_luserdata_const(lua_State *L, const orxANIMPOINTER* src);
LORX_API orxANIMPOINTER* lorx_luserdata_to_orxANIMPOINTER(lua_State *L, int i);
LORX_API const orxANIMPOINTER* lorx_luserdata_to_orxANIMPOINTER_const(lua_State *L, int i);
LORX_API int lorx_orxANIMSET_to_luserdata(lua_State *L, orxANIMSET* src);
LORX_API int lorx_orxANIMSET_to_luserdata_const(lua_State *L, const orxANIMSET* src);
LORX_API orxANIMSET* lorx_luserdata_to_orxANIMSET(lua_State *L, int i);
LORX_API const orxANIMSET* lorx_luserdata_to_orxANIMSET_const(lua_State *L, int i);
LORX_API int lorx_orxANIMSET_LINK_TABLE_to_luserdata(lua_State *L, orxANIMSET_LINK_TABLE* src);
LORX_API int lorx_orxANIMSET_LINK_TABLE_to_luserdata_const(lua_State *L, const orxANIMSET_LINK_TABLE* src);
LORX_API orxANIMSET_LINK_TABLE* lorx_luserdata_to_orxANIMSET_LINK_TABLE(lua_State *L, int i);
LORX_API const orxANIMSET_LINK_TABLE* lorx_luserdata_to_orxANIMSET_LINK_TABLE_const(lua_State *L, int i);
LORX_API int lorx_orxANIM_CUSTOM_EVENT_to_luserdata_struct(lua_State *L, const orxANIM_CUSTOM_EVENT *src);
LORX_API orxANIM_CUSTOM_EVENT lorx_luserdata_to_orxANIM_CUSTOM_EVENT_struct(lua_State *L, int i);
LORX_API orxANIM_CUSTOM_EVENT* lorx_luserdata_to_orxANIM_CUSTOM_EVENT(lua_State *L, int i);
LORX_API const orxANIM_CUSTOM_EVENT* lorx_luserdata_to_orxANIM_CUSTOM_EVENT_const(lua_State *L, int i);
LORX_API int lorx_orxBITMAP_to_luserdata(lua_State *L, orxBITMAP* src);
LORX_API int lorx_orxBITMAP_to_luserdata_const(lua_State *L, const orxBITMAP* src);
LORX_API orxBITMAP* lorx_luserdata_to_orxBITMAP(lua_State *L, int i);
LORX_API const orxBITMAP* lorx_luserdata_to_orxBITMAP_const(lua_State *L, int i);
LORX_API int lorx_orxBODY_to_luserdata(lua_State *L, orxBODY* src);
LORX_API int lorx_orxBODY_to_luserdata_const(lua_State *L, const orxBODY* src);
LORX_API orxBODY* lorx_luserdata_to_orxBODY(lua_State *L, int i);
LORX_API const orxBODY* lorx_luserdata_to_orxBODY_const(lua_State *L, int i);
LORX_API int lorx_orxBODY_JOINT_to_luserdata(lua_State *L, orxBODY_JOINT* src);
LORX_API int lorx_orxBODY_JOINT_to_luserdata_const(lua_State *L, const orxBODY_JOINT* src);
LORX_API orxBODY_JOINT* lorx_luserdata_to_orxBODY_JOINT(lua_State *L, int i);
LORX_API const orxBODY_JOINT* lorx_luserdata_to_orxBODY_JOINT_const(lua_State *L, int i);
LORX_API int lorx_orxBODY_PART_to_luserdata(lua_State *L, orxBODY_PART* src);
LORX_API int lorx_orxBODY_PART_to_luserdata_const(lua_State *L, const orxBODY_PART* src);
LORX_API orxBODY_PART* lorx_luserdata_to_orxBODY_PART(lua_State *L, int i);
LORX_API const orxBODY_PART* lorx_luserdata_to_orxBODY_PART_const(lua_State *L, int i);
LORX_API int lorx_orxCAMERA_to_luserdata(lua_State *L, orxCAMERA* src);
LORX_API int lorx_orxCAMERA_to_luserdata_const(lua_State *L, const orxCAMERA* src);
LORX_API orxCAMERA* lorx_luserdata_to_orxCAMERA(lua_State *L, int i);
LORX_API const orxCAMERA* lorx_luserdata_to_orxCAMERA_const(lua_State *L, int i);
LORX_API int lorx_orxCHARACTER_GLYPH_to_luserdata_struct(lua_State *L, const orxCHARACTER_GLYPH *src);
LORX_API orxCHARACTER_GLYPH lorx_luserdata_to_orxCHARACTER_GLYPH_struct(lua_State *L, int i);
LORX_API orxCHARACTER_GLYPH* lorx_luserdata_to_orxCHARACTER_GLYPH(lua_State *L, int i);
LORX_API const orxCHARACTER_GLYPH* lorx_luserdata_to_orxCHARACTER_GLYPH_const(lua_State *L, int i);
LORX_API int lorx_orxCHARACTER_MAP_to_luserdata(lua_State *L, orxCHARACTER_MAP* src);
LORX_API int lorx_orxCHARACTER_MAP_to_luserdata_const(lua_State *L, const orxCHARACTER_MAP* src);
LORX_API orxCHARACTER_MAP* lorx_luserdata_to_orxCHARACTER_MAP(lua_State *L, int i);
LORX_API const orxCHARACTER_MAP* lorx_luserdata_to_orxCHARACTER_MAP_const(lua_State *L, int i);
LORX_API int lorx_orxCLOCK_to_luserdata(lua_State *L, orxCLOCK* src);
LORX_API int lorx_orxCLOCK_to_luserdata_const(lua_State *L, const orxCLOCK* src);
LORX_API orxCLOCK* lorx_luserdata_to_orxCLOCK(lua_State *L, int i);
LORX_API const orxCLOCK* lorx_luserdata_to_orxCLOCK_const(lua_State *L, int i);
LORX_API int lorx_orxCLOCK_INFO_to_luserdata(lua_State *L, orxCLOCK_INFO* src);
LORX_API int lorx_orxCLOCK_INFO_to_luserdata_const(lua_State *L, const orxCLOCK_INFO* src);
LORX_API orxCLOCK_INFO* lorx_luserdata_to_orxCLOCK_INFO(lua_State *L, int i);
LORX_API const orxCLOCK_INFO* lorx_luserdata_to_orxCLOCK_INFO_const(lua_State *L, int i);
LORX_API int lorx_orxCOLOR_to_luserdata_struct(lua_State *L, const orxCOLOR *src);
LORX_API orxCOLOR lorx_luserdata_to_orxCOLOR_struct(lua_State *L, int i);
LORX_API orxCOLOR* lorx_luserdata_to_orxCOLOR(lua_State *L, int i);
LORX_API const orxCOLOR* lorx_luserdata_to_orxCOLOR_const(lua_State *L, int i);
LORX_API int lorx_orxCOMMAND_VAR_to_luserdata_struct(lua_State *L, const orxCOMMAND_VAR *src);
LORX_API orxCOMMAND_VAR lorx_luserdata_to_orxCOMMAND_VAR_struct(lua_State *L, int i);
LORX_API orxCOMMAND_VAR* lorx_luserdata_to_orxCOMMAND_VAR(lua_State *L, int i);
LORX_API const orxCOMMAND_VAR* lorx_luserdata_to_orxCOMMAND_VAR_const(lua_State *L, int i);
LORX_API int lorx_orxDISPLAY_MESH_to_luserdata(lua_State *L, orxDISPLAY_MESH* src);
LORX_API int lorx_orxDISPLAY_MESH_to_luserdata_const(lua_State *L, const orxDISPLAY_MESH* src);
LORX_API orxDISPLAY_MESH* lorx_luserdata_to_orxDISPLAY_MESH(lua_State *L, int i);
LORX_API const orxDISPLAY_MESH* lorx_luserdata_to_orxDISPLAY_MESH_const(lua_State *L, int i);
LORX_API int lorx_orxDISPLAY_TRANSFORM_to_luserdata_struct(lua_State *L, const orxDISPLAY_TRANSFORM *src);
LORX_API orxDISPLAY_TRANSFORM lorx_luserdata_to_orxDISPLAY_TRANSFORM_struct(lua_State *L, int i);
LORX_API orxDISPLAY_TRANSFORM* lorx_luserdata_to_orxDISPLAY_TRANSFORM(lua_State *L, int i);
LORX_API const orxDISPLAY_TRANSFORM* lorx_luserdata_to_orxDISPLAY_TRANSFORM_const(lua_State *L, int i);
LORX_API int lorx_orxDISPLAY_VIDEO_MODE_to_luserdata_struct(lua_State *L, const orxDISPLAY_VIDEO_MODE *src);
LORX_API orxDISPLAY_VIDEO_MODE lorx_luserdata_to_orxDISPLAY_VIDEO_MODE_struct(lua_State *L, int i);
LORX_API orxDISPLAY_VIDEO_MODE* lorx_luserdata_to_orxDISPLAY_VIDEO_MODE(lua_State *L, int i);
LORX_API const orxDISPLAY_VIDEO_MODE* lorx_luserdata_to_orxDISPLAY_VIDEO_MODE_const(lua_State *L, int i);
LORX_API int lorx_orxFILE_to_luserdata(lua_State *L, orxFILE* src);
LORX_API int lorx_orxFILE_to_luserdata_const(lua_State *L, const orxFILE* src);
LORX_API orxFILE* lorx_luserdata_to_orxFILE(lua_State *L, int i);
LORX_API const orxFILE* lorx_luserdata_to_orxFILE_const(lua_State *L, int i);
LORX_API int lorx_orxFILE_INFO_to_luserdata_struct(lua_State *L, const orxFILE_INFO *src);
LORX_API orxFILE_INFO lorx_luserdata_to_orxFILE_INFO_struct(lua_State *L, int i);
LORX_API orxFILE_INFO* lorx_luserdata_to_orxFILE_INFO(lua_State *L, int i);
LORX_API const orxFILE_INFO* lorx_luserdata_to_orxFILE_INFO_const(lua_State *L, int i);
LORX_API int lorx_orxFONT_to_luserdata(lua_State *L, orxFONT* src);
LORX_API int lorx_orxFONT_to_luserdata_const(lua_State *L, const orxFONT* src);
LORX_API orxFONT* lorx_luserdata_to_orxFONT(lua_State *L, int i);
LORX_API const orxFONT* lorx_luserdata_to_orxFONT_const(lua_State *L, int i);
LORX_API int lorx_orxFRAME_to_luserdata(lua_State *L, orxFRAME* src);
LORX_API int lorx_orxFRAME_to_luserdata_const(lua_State *L, const orxFRAME* src);
LORX_API orxFRAME* lorx_luserdata_to_orxFRAME(lua_State *L, int i);
LORX_API const orxFRAME* lorx_luserdata_to_orxFRAME_const(lua_State *L, int i);
LORX_API int lorx_orxFX_to_luserdata(lua_State *L, orxFX* src);
LORX_API int lorx_orxFX_to_luserdata_const(lua_State *L, const orxFX* src);
LORX_API orxFX* lorx_luserdata_to_orxFX(lua_State *L, int i);
LORX_API const orxFX* lorx_luserdata_to_orxFX_const(lua_State *L, int i);
LORX_API int lorx_orxFXPOINTER_to_luserdata(lua_State *L, orxFXPOINTER* src);
LORX_API int lorx_orxFXPOINTER_to_luserdata_const(lua_State *L, const orxFXPOINTER* src);
LORX_API orxFXPOINTER* lorx_luserdata_to_orxFXPOINTER(lua_State *L, int i);
LORX_API const orxFXPOINTER* lorx_luserdata_to_orxFXPOINTER_const(lua_State *L, int i);
LORX_API int lorx_orxGRAPHIC_to_luserdata(lua_State *L, orxGRAPHIC* src);
LORX_API int lorx_orxGRAPHIC_to_luserdata_const(lua_State *L, const orxGRAPHIC* src);
LORX_API orxGRAPHIC* lorx_luserdata_to_orxGRAPHIC(lua_State *L, int i);
LORX_API const orxGRAPHIC* lorx_luserdata_to_orxGRAPHIC_const(lua_State *L, int i);
LORX_API int lorx_orxOBJECT_to_luserdata(lua_State *L, orxOBJECT* src);
LORX_API int lorx_orxOBJECT_to_luserdata_const(lua_State *L, const orxOBJECT* src);
LORX_API orxOBJECT* lorx_luserdata_to_orxOBJECT(lua_State *L, int i);
LORX_API const orxOBJECT* lorx_luserdata_to_orxOBJECT_const(lua_State *L, int i);
LORX_API int lorx_orxOBOX_to_luserdata_struct(lua_State *L, const orxOBOX *src);
LORX_API orxOBOX lorx_luserdata_to_orxOBOX_struct(lua_State *L, int i);
LORX_API orxOBOX* lorx_luserdata_to_orxOBOX(lua_State *L, int i);
LORX_API const orxOBOX* lorx_luserdata_to_orxOBOX_const(lua_State *L, int i);
LORX_API int lorx_orxPHYSICS_BODY_to_luserdata(lua_State *L, orxPHYSICS_BODY* src);
LORX_API int lorx_orxPHYSICS_BODY_to_luserdata_const(lua_State *L, const orxPHYSICS_BODY* src);
LORX_API orxPHYSICS_BODY* lorx_luserdata_to_orxPHYSICS_BODY(lua_State *L, int i);
LORX_API const orxPHYSICS_BODY* lorx_luserdata_to_orxPHYSICS_BODY_const(lua_State *L, int i);
LORX_API int lorx_orxPHYSICS_BODY_JOINT_to_luserdata(lua_State *L, orxPHYSICS_BODY_JOINT* src);
LORX_API int lorx_orxPHYSICS_BODY_JOINT_to_luserdata_const(lua_State *L, const orxPHYSICS_BODY_JOINT* src);
LORX_API orxPHYSICS_BODY_JOINT* lorx_luserdata_to_orxPHYSICS_BODY_JOINT(lua_State *L, int i);
LORX_API const orxPHYSICS_BODY_JOINT* lorx_luserdata_to_orxPHYSICS_BODY_JOINT_const(lua_State *L, int i);
LORX_API int lorx_orxPHYSICS_BODY_PART_to_luserdata(lua_State *L, orxPHYSICS_BODY_PART* src);
LORX_API int lorx_orxPHYSICS_BODY_PART_to_luserdata_const(lua_State *L, const orxPHYSICS_BODY_PART* src);
LORX_API orxPHYSICS_BODY_PART* lorx_luserdata_to_orxPHYSICS_BODY_PART(lua_State *L, int i);
LORX_API const orxPHYSICS_BODY_PART* lorx_luserdata_to_orxPHYSICS_BODY_PART_const(lua_State *L, int i);
LORX_API int lorx_orxRGBA_to_luserdata_struct(lua_State *L, const orxRGBA *src);
LORX_API orxRGBA lorx_luserdata_to_orxRGBA_struct(lua_State *L, int i);
LORX_API orxRGBA* lorx_luserdata_to_orxRGBA(lua_State *L, int i);
LORX_API const orxRGBA* lorx_luserdata_to_orxRGBA_const(lua_State *L, int i);
LORX_API int lorx_orxSHADER_to_luserdata(lua_State *L, orxSHADER* src);
LORX_API int lorx_orxSHADER_to_luserdata_const(lua_State *L, const orxSHADER* src);
LORX_API orxSHADER* lorx_luserdata_to_orxSHADER(lua_State *L, int i);
LORX_API const orxSHADER* lorx_luserdata_to_orxSHADER_const(lua_State *L, int i);
LORX_API int lorx_orxSHADERPOINTER_to_luserdata(lua_State *L, orxSHADERPOINTER* src);
LORX_API int lorx_orxSHADERPOINTER_to_luserdata_const(lua_State *L, const orxSHADERPOINTER* src);
LORX_API orxSHADERPOINTER* lorx_luserdata_to_orxSHADERPOINTER(lua_State *L, int i);
LORX_API const orxSHADERPOINTER* lorx_luserdata_to_orxSHADERPOINTER_const(lua_State *L, int i);
LORX_API int lorx_orxSOUND_to_luserdata(lua_State *L, orxSOUND* src);
LORX_API int lorx_orxSOUND_to_luserdata_const(lua_State *L, const orxSOUND* src);
LORX_API orxSOUND* lorx_luserdata_to_orxSOUND(lua_State *L, int i);
LORX_API const orxSOUND* lorx_luserdata_to_orxSOUND_const(lua_State *L, int i);
LORX_API int lorx_orxSOUNDPOINTER_to_luserdata(lua_State *L, orxSOUNDPOINTER* src);
LORX_API int lorx_orxSOUNDPOINTER_to_luserdata_const(lua_State *L, const orxSOUNDPOINTER* src);
LORX_API orxSOUNDPOINTER* lorx_luserdata_to_orxSOUNDPOINTER(lua_State *L, int i);
LORX_API const orxSOUNDPOINTER* lorx_luserdata_to_orxSOUNDPOINTER_const(lua_State *L, int i);
LORX_API int lorx_orxSOUNDSYSTEM_SAMPLE_to_luserdata(lua_State *L, orxSOUNDSYSTEM_SAMPLE* src);
LORX_API int lorx_orxSOUNDSYSTEM_SAMPLE_to_luserdata_const(lua_State *L, const orxSOUNDSYSTEM_SAMPLE* src);
LORX_API orxSOUNDSYSTEM_SAMPLE* lorx_luserdata_to_orxSOUNDSYSTEM_SAMPLE(lua_State *L, int i);
LORX_API const orxSOUNDSYSTEM_SAMPLE* lorx_luserdata_to_orxSOUNDSYSTEM_SAMPLE_const(lua_State *L, int i);
LORX_API int lorx_orxSOUNDSYSTEM_SOUND_to_luserdata(lua_State *L, orxSOUNDSYSTEM_SOUND* src);
LORX_API int lorx_orxSOUNDSYSTEM_SOUND_to_luserdata_const(lua_State *L, const orxSOUNDSYSTEM_SOUND* src);
LORX_API orxSOUNDSYSTEM_SOUND* lorx_luserdata_to_orxSOUNDSYSTEM_SOUND(lua_State *L, int i);
LORX_API const orxSOUNDSYSTEM_SOUND* lorx_luserdata_to_orxSOUNDSYSTEM_SOUND_const(lua_State *L, int i);
LORX_API int lorx_orxSOUND_FILTER_DATA_to_luserdata_struct(lua_State *L, const orxSOUND_FILTER_DATA *src);
LORX_API orxSOUND_FILTER_DATA lorx_luserdata_to_orxSOUND_FILTER_DATA_struct(lua_State *L, int i);
LORX_API orxSOUND_FILTER_DATA* lorx_luserdata_to_orxSOUND_FILTER_DATA(lua_State *L, int i);
LORX_API const orxSOUND_FILTER_DATA* lorx_luserdata_to_orxSOUND_FILTER_DATA_const(lua_State *L, int i);
LORX_API int lorx_orxSOUND_STREAM_INFO_to_luserdata(lua_State *L, orxSOUND_STREAM_INFO* src);
LORX_API int lorx_orxSOUND_STREAM_INFO_to_luserdata_const(lua_State *L, const orxSOUND_STREAM_INFO* src);
LORX_API orxSOUND_STREAM_INFO* lorx_luserdata_to_orxSOUND_STREAM_INFO(lua_State *L, int i);
LORX_API const orxSOUND_STREAM_INFO* lorx_luserdata_to_orxSOUND_STREAM_INFO_const(lua_State *L, int i);
LORX_API int lorx_orxSOUND_STREAM_PACKET_to_luserdata(lua_State *L, orxSOUND_STREAM_PACKET* src);
LORX_API int lorx_orxSOUND_STREAM_PACKET_to_luserdata_const(lua_State *L, const orxSOUND_STREAM_PACKET* src);
LORX_API orxSOUND_STREAM_PACKET* lorx_luserdata_to_orxSOUND_STREAM_PACKET(lua_State *L, int i);
LORX_API const orxSOUND_STREAM_PACKET* lorx_luserdata_to_orxSOUND_STREAM_PACKET_const(lua_State *L, int i);
LORX_API int lorx_orxSPAWNER_to_luserdata(lua_State *L, orxSPAWNER* src);
LORX_API int lorx_orxSPAWNER_to_luserdata_const(lua_State *L, const orxSPAWNER* src);
LORX_API orxSPAWNER* lorx_luserdata_to_orxSPAWNER(lua_State *L, int i);
LORX_API const orxSPAWNER* lorx_luserdata_to_orxSPAWNER_const(lua_State *L, int i);
LORX_API int lorx_orxSTRUCTURE_to_luserdata(lua_State *L, orxSTRUCTURE* src);
LORX_API int lorx_orxSTRUCTURE_to_luserdata_const(lua_State *L, const orxSTRUCTURE* src);
LORX_API orxSTRUCTURE* lorx_luserdata_to_orxSTRUCTURE(lua_State *L, int i);
LORX_API const orxSTRUCTURE* lorx_luserdata_to_orxSTRUCTURE_const(lua_State *L, int i);
LORX_API int lorx_orxTEXT_to_luserdata(lua_State *L, orxTEXT* src);
LORX_API int lorx_orxTEXT_to_luserdata_const(lua_State *L, const orxTEXT* src);
LORX_API orxTEXT* lorx_luserdata_to_orxTEXT(lua_State *L, int i);
LORX_API const orxTEXT* lorx_luserdata_to_orxTEXT_const(lua_State *L, int i);
LORX_API int lorx_orxTEXTURE_to_luserdata(lua_State *L, orxTEXTURE* src);
LORX_API int lorx_orxTEXTURE_to_luserdata_const(lua_State *L, const orxTEXTURE* src);
LORX_API orxTEXTURE* lorx_luserdata_to_orxTEXTURE(lua_State *L, int i);
LORX_API const orxTEXTURE* lorx_luserdata_to_orxTEXTURE_const(lua_State *L, int i);
LORX_API int lorx_orxTHREAD_SEMAPHORE_to_luserdata(lua_State *L, orxTHREAD_SEMAPHORE* src);
LORX_API int lorx_orxTHREAD_SEMAPHORE_to_luserdata_const(lua_State *L, const orxTHREAD_SEMAPHORE* src);
LORX_API orxTHREAD_SEMAPHORE* lorx_luserdata_to_orxTHREAD_SEMAPHORE(lua_State *L, int i);
LORX_API const orxTHREAD_SEMAPHORE* lorx_luserdata_to_orxTHREAD_SEMAPHORE_const(lua_State *L, int i);
LORX_API int lorx_orxTIMELINE_to_luserdata(lua_State *L, orxTIMELINE* src);
LORX_API int lorx_orxTIMELINE_to_luserdata_const(lua_State *L, const orxTIMELINE* src);
LORX_API orxTIMELINE* lorx_luserdata_to_orxTIMELINE(lua_State *L, int i);
LORX_API const orxTIMELINE* lorx_luserdata_to_orxTIMELINE_const(lua_State *L, int i);
LORX_API int lorx_orxVECTOR_to_luserdata_struct(lua_State *L, const orxVECTOR *src);
LORX_API orxVECTOR lorx_luserdata_to_orxVECTOR_struct(lua_State *L, int i);
LORX_API orxVECTOR* lorx_luserdata_to_orxVECTOR(lua_State *L, int i);
LORX_API const orxVECTOR* lorx_luserdata_to_orxVECTOR_const(lua_State *L, int i);
LORX_API int lorx_orxVIEWPORT_to_luserdata(lua_State *L, orxVIEWPORT* src);
LORX_API int lorx_orxVIEWPORT_to_luserdata_const(lua_State *L, const orxVIEWPORT* src);
LORX_API orxVIEWPORT* lorx_luserdata_to_orxVIEWPORT(lua_State *L, int i);
LORX_API const orxVIEWPORT* lorx_luserdata_to_orxVIEWPORT_const(lua_State *L, int i);

#endif /* __LORX_CONUTYPE_H__ */